### ISSUE TITLE
Bounty: equihash algo (0.5 BTC)

### ISSUE THREAD

**Issue by coolsd** [tpruvot/yiimp#109]
We'd like to have the equihash algo coded for this pool. Bounty is 0.5BTC. Please PM if interested as this will be private code.

Thanks!

mail:chne2001@gmail.com

**Comment by BaalMcKloud** [comment]
algo is allready added..

**Comment by coolsd** [comment]
algo is allready added..
????

**Comment by coolsd** [comment]
@BaalMcKloud Please PM

**Comment by BaalMcKloud** [comment]
http://yiimp.ccminer.org from @tpruvot  and  http://zpool.ca from @crackfoo using it.
maybe you can get the code from them. both running yiimp pools.

**Comment by tpruvot** [comment]
its not on sale for now, unfinished
