### ISSUE TITLE
Some strange arbitrary calculations

### ISSUE THREAD

**Issue by CryptoDwarf** [tpruvot/yiimp#11]
In yiimp/web/yaamp/core/backend/stats.php, there is a strange calculation calculating user hashrate:

function BackendStatsUpdate2()

		$percent = 20;[/b]
		$user_rate = yaamp_user_rate($item['userid'], $item['algo']);
		$stats->hashrate = round(($stats->hashrate*(100-$percent) + $user_rate*$percent) / 100);
		if($stats->hashrate < 1000) $stats->hashrate = 0;

This seems to be manipulating user hash rate calculations in a way I cannot get my head around. Further up the code, the pool hash rate calculations have had this strange calculation commented out. 

		$pool_rate = yaamp_pool_rate($algo);
		$stats->hashrate = $pool_rate;	//round(($stats->hashrate*(100-$percent) + $pool_rate*$percent) / 100);
		$pool_rate_bad = yaamp_pool_rate_bad($algo);
		$stats->hashrate_bad = $pool_rate_bad;	//round(($stats->hashrate_bad*(100-$percent) + $pool_rate_bad*$percent) / 100);

Perhaps this function needs updating too?

This strange calculation is also found in yiimp/web/yaamp/core/backend/markets.php on the calculation of market bid / mid prices:

function AverageIncrement($value1, $value2)
{
	$percent = 80;
	$value = ($value1*(100-$percent) + $value2*$percent) / 100;
	return $value;
}

		$price2 = ($ticker->result[0]->Bid+$ticker->result[0]->Ask)/2;
		$market->price2 = AverageIncrement($market->price2, $price2);
		$market->price = AverageIncrement($market->price, $ticker->result[0]->Bid);

Yet again, the same strange calculation but applied to a different aspect of the code. In this case the function may provide some kind of market price smoothing function. However, I consider this market price manipulation will cause incorrect profitability figures, and cause bad trading function decisions. I would remove it.

Can you investigate the above strange arbitrary calculations please?

**Comment by tpruvot** [comment]
i will not change that, seems fine to me and i don't really care about trading... if you find a better way, i can test it but for me its correct... and the same for all.

Again, mining doesnt imply auto dumping...

**Comment by CryptoDwarf** [comment]
So what is the logic behind the user hash rate calculation?

**Comment by CryptoDwarf** [comment]
Profitably is being calculated on the coin price

yiimp/web/yaamp/core/functions/yaamp.php

function yaamp_profitability($coin)
{
	if(!$coin->difficulty) return 0;
	$btcmhd = 20116.56761169 / $coin->difficulty * $coin->reward * $coin->price;
	if(!$coin->auxpow && $coin->rpcencoding == 'POW')
	{
		$listaux = getdbolist('db_coins', "enable and visible and auto_ready and auxpow and algo='$coin->algo'");
		foreach($listaux as $aux)
		{
			if(!$aux->difficulty) continue;
			$btcmhdaux = 20116.56761169 / $aux->difficulty * $aux->reward * $aux->price;
			$btcmhd += $btcmhdaux;
		}
	}
	if($coin->algo == 'sha256') $btcmhd *= 1000;
	return $btcmhd;
}

Which is being determined from the best market price:

yiimp/blob/yiimp/web/yaamp/core/backend/markets.php

Yet the market price is a manipulated market price. So the coin profitability seems to be effected.
