### ISSUE TITLE
Bounty:Need to set fees for individual users (0.1btc)

### ISSUE THREAD

**Issue by coolsd** [tpruvot/yiimp#110]
Need to set fees for individual users. Looking for someone to finish this off for 0.1 BTC bounty.

Thanks!

**Comment by coolsd** [comment]
Thanks！

**Comment by Tristian** [comment]
Whenever you have a moment :-)
12Nam4bHL6hmce3QYfFH1EnBZWXFqqDo6N

**Comment by coolsd** [comment]
// Per 'user' fee override
$configUserFees = array(
	'198.11.220.46' => 0.1,
);

Invalid setting，Not work。


![11](https://cloud.githubusercontent.com/assets/7413058/26230548/557aad9a-3c7c-11e7-8e89-d58637da632a.jpg)

**Comment by Tristian** [comment]
Apologies. The users should be defined using their coin address, not IP address. a1c2c691

**Comment by coolsd** [comment]
![Uploading 44.jpg…]()

**Comment by coolsd** [comment]
![33](https://cloud.githubusercontent.com/assets/7413058/26272290/f175127e-3d46-11e7-896b-ee348185eaed.jpg)

**Comment by coolsd** [comment]
![44](https://cloud.githubusercontent.com/assets/7413058/26272294/fc2c6884-3d46-11e7-9552-64c408f8bd1d.jpg)

**Comment by coolsd** [comment]
![33](https://cloud.githubusercontent.com/assets/7413058/26272439/ae5f796c-3d4a-11e7-9183-094b1aaa812b.jpg)
![44](https://cloud.githubusercontent.com/assets/7413058/26272442/b6766962-3d4a-11e7-8028-35997fd4ac59.jpg)

**Comment by Tristian** [comment]
Can you try the latest commit?
Also, the config option should be between 0 and 1. A value of 5 is actually 500%.

**Comment by coolsd** [comment]
![33](https://cloud.githubusercontent.com/assets/7413058/26280680/018ed382-3e11-11e7-9ab2-5cf4545330a9.jpg)
![44](https://cloud.githubusercontent.com/assets/7413058/26280691/24bd9262-3e11-11e7-9ea2-acb344527c5c.jpg)

**Comment by coolsd** [comment]
???

**Comment by Tristian** [comment]
Sorry. Been busy. I won't be able to work on this until Tuesday.

**Comment by Tristian** [comment]
I have time to actually test this now. I have a fix if can confirm you are willing to pay the 0.1btc bounty.

**Comment by Tristian** [comment]
@coolsd I've pushed the fix even though I haven't heard from you. I hope you do the right thing.
