### ISSUE TITLE
BUG Connecting workers to 5000+ will be a problem, In the same coin.

### ISSUE THREAD

**Issue by coolsd** [tpruvot/yiimp#111]
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28421 ms
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28454 ms
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28490 ms
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28526 ms
22:09:17: submit 218.76.84.71 (uid 12) 2, 00000000, 59131eee, 3e2a2a13, 1263.000/64.000
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28563 ms
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28601 ms
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28637 ms
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28675 ms
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28711 ms
22:09:17: submit 58.51.240.199 (uid 12) 2, 01000000, 59131eee, a2b5e119, 1919.000/64.000
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28748 ms
22:09:17: delay rpc_call 192.168.1.130:14330 validateaddress in 28786 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 28823 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 28860 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 28884 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 28921 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 28958 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 28995 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29031 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29067 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29103 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 31803 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29177 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29214 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29250 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29286 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29316 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29350 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29388 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29423 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29461 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29498 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29535 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29572 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29608 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29646 ms
22:09:18: delay rpc_call 192.168.1.130:14330 validateaddress in 29682 ms
22:09:19: delay rpc_call 192.168.1.130:14330 validateaddress in 29704 ms
22:09:19: delay rpc_call 192.168.1.130:14330 validateaddress in 29741 ms
22:09:19: delay rpc_call 192.168.1.130:14330 validateaddress in 29780 ms
22:09:19: delay rpc_call 192.168.1.130:14330 validateaddress in 29815 ms
22:09:19: delay rpc_call 192.168.1.130:14330 validateaddress in 29851 ms
22:09:19: delay rpc_call 192.168.1.130:14330 validateaddress in 29887 ms
22:09:19: delay rpc_call 192.168.1.130:14330 validateaddress in 29924 ms

./run.sh: line 11:  3779 Segmentation fault      ./stratum config/$1
22:11:34: 2017-05-10 starting stratum for lbry on yiimp.***.com:3334
22:11:34: connecting to coind LBC

**Comment by tpruvot** [comment]
can be resolved using a sleep on start of client_thread (client.cpp) - testing different solutions locally

**Comment by tpruvot** [comment]
see commit 07ff36c86667f7ecc8531c5c99607b0070fb02df
