### ISSUE TITLE
Multi-algo (Digitalcoin specifically; may affect others)

### ISSUE THREAD

**Issue by barrystyle** [tpruvot/yiimp#113]
Have added/configured DigitalCoin to YIIMP, however when block is found; is rejected.

X11 Stratum instance:
*** REJECTED :( DigitalCoin block 2568258 2 txs

Digitalcoin debug.log:
2017-05-11 10:51:39 ERROR: CheckProofOfWork(algo=1) : hash doesn't match nBits
2017-05-11 10:51:39 ERROR: CheckBlock() : proof of work failed
2017-05-11 10:51:39 ERROR: ProcessBlock() : CheckBlock FAILED

Please note this is not related to https://bitcointalk.org/index.php?topic=785601.0 (Algorithm Control - If the last three blocks were discovered by the same algorithm, the fourth block will be rejected until its found by one of the other two algorithms. This prevents directed attacks on the network from any single algorithm.) - as well over 10-15 blocks have been rejected with identical error.

james

**Comment by tpruvot** [comment]
a wallet instance cant change its mining algo on the fly, you need 2 instances with the proper algo=xxx in their .conf if you are mining two algos

**Comment by barrystyle** [comment]
Legend; this is not clear in any of the multi-algorithm coins, thanks for clearing that up.
