### ISSUE TITLE
Payout check for DCR fails

### ISSUE THREAD

**Issue by crackfoo** [tpruvot/yiimp#12]
./yiimp payout check DCR
DshciZZx5iCLRXntQAprzCs5jWC3BhTVQz2 payouts since 2016-02-21 Sun Feb 21 22:01:09 2016: 1
PHP Error[2]: Invalid argument supplied for foreach()
    in file /pool/web/yaamp/commands/PayoutCommand.php at line 121
#0 /pool/web/yaamp/commands/PayoutCommand.php(43): PayoutCommand->checkPayouts()
#1 /pool/web/framework-1.0.8/console/CConsoleCommandRunner.php(71): PayoutCommand->run()
#2 /pool/web/framework-1.0.8/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#3 /pool/web/framework-1.0.8/base/CApplication.php(134): CConsoleApplication->processRequest()
#4 /pool/web/yaamp/yiic.php(31): CConsoleApplication->run()

**Comment by tpruvot** [comment]
DCR listtransactions is not compatible with this command but... will add the extra check

https://github.com/decred/dcrwallet/issues/39
