### ISSUE TITLE
BTC Mining http://pool.cryptominer.co.uk/ not giving me properly payout.

### ISSUE THREAD

**Issue by prasadh5** [tpruvot/yiimp#120]
Hi
earlier i got payour on every 24 hr of my Antminer S9 machine ,but from last 7 days i did not get proper payout its very delayed. any issue with mining pool ?
i like this mining pool very much, i dont want to leave this pool, pls solve the issue soon.
reply me on mail as well 
prasadh.chavaan@gmail.com

**Comment by tpruvot** [comment]
right, well, you are not at the right place for the support :/ i dont know the owner of this site

**Comment by crackfoo** [comment]
If you want to mine sha256, then point it to www.zpool.ca

**Comment by prasadh5** [comment]
Ok looking nice.
Can you guide me how to configure this script to miner so.
I did not understand PORT ?
What should I write there.
Or send me dummy sample text.


-o stratum+tcp://<algo>.mine.zpool.ca:<PORT> -u <WALLET_ADDRESS> [-p
<OPTIONS>]
