### ISSUE TITLE
How does WIN wallet use blocknotify?

### ISSUE THREAD

**Issue by coolsd** [tpruvot/yiimp#121]
How does WIN wallet use blocknotify?
WIN wallet does not automatically update blocks

**Comment by mooncoindev** [comment]
Use cygwin/visual studio to compile blocknotify for win32; works correctly.
All wallets have a blocknotify function (check command line options).

**Comment by barrystyle** [comment]
Use cygwin/visual studio to compile blocknotify for win32; works correctly.
All wallets have a blocknotify function (check command line options).

**Comment by coolsd** [comment]
Do you have a compiled one?

**Comment by coolsd** [comment]
Blocknotify has been compiled, but it doesn't work. Do you have a complete example?

**Comment by barrystyle** [comment]
Need to be a bit more specific with 'it doesnt work'.
When you run it from a command prompt, do you get any output?

**Comment by coolsd** [comment]
not any output , wallet does not automatically update blocks.

wallet.exe -datadir=.\data\ -conf=coin.conf -blocknotify=E:\qb\blocknotify 139.224.*.*:3533 1695 %s

**Comment by tpruvot** [comment]
In the .conf
