### ISSUE TITLE
Issue with coins not showing

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [tpruvot/yiimp#124]
Hello, I have been following your readme in the attempt to setup your pool software. 

I have gotten so far as having my full sql database up and running, and the command "yiimp checkup" shows no issues. If I look through my sql database I can see that blocknotify is working as some information is populating (such as version and block height).

I have "auto-ready" and "visible" set to 1, and yet I still have no coins showing up. 

Also, and this may have nothing to do with the issue, but when on the frontend and clicking links i keep getting "site/PAGE" not found, where PAGE is whatever Im trying to view (eg. adminRights or mining).

Any assistance would be greatly appreciated.

**Comment by tpruvot** [comment]
you start all to be me with your noob "issues" flooding my mail box.. we have an IRC channel for questions

**Comment by l8nit3tr0ubl3** [comment]
I believe i understand my issue now. I apolpgize for "bugging" with my issue and will not be opening another, especially since this was a stupid conf issue on my part. In my defense i did read all other issues before opening this one....
