### ISSUE TITLE
Per user balance not increasing..

### ISSUE THREAD

**Issue by barrystyle** [tpruvot/yiimp#126]
Unable to solve this on first install; wiped and reinstalled again, user balance shows earnt BTC correctly but Balance remains zero.
This is from latest 'next' branch, with all commits up to 'a2aaf2b' applied.

http://i.imgur.com/Xrg19BJ.png (screenshot)

**Comment by tpruvot** [comment]
you start all to be me with your noob "issues" flooding my mail box.. we have an IRC channel for questions

**Comment by mooncoindev** [comment]
Willing to pay to get this issue resolved; have reverted back and balances still zero'd.
Everything else works correctly, coins are sent to exchange after generation and BTC is sent back to the pool wallet.

**Comment by barrystyle** [comment]
Willing to pay to get this issue resolved; have reverted back and balances still zero'd.

Everything else works correctly, coins are sent to exchange after generation and BTC is sent back to the pool wallet.
