### ISSUE TITLE
Add coin profit to api

### ISSUE THREAD

**Issue by snakethejake81** [tpruvot/yiimp#128]
Can you add the individual coin profitability stats to the Currencies api?

Or possibly expand the Status api call with individual coins?

I am working on adapting a mining script that I use on zpool to work with YiiMP but since it doesn't auto select the coins for pools I would need this info to select the most profitable coin.

Thanks,

Jake

**Comment by tpruvot** [comment]
e9ea21b395f3d18d2358f7fefc3b41a5aaa7403f
