### ISSUE TITLE
eMark (DEM) Blocks not accepted

### ISSUE THREAD

**Issue by crackfoo** [tpruvot/yiimp#13]
with RPC type PoS, blocks continue to be rejected. With PoW they do not decode at all with a wallet errors of TX not first in coinbase, indicating it should be PoS.

Any ideas what might be the issue?

**Comment by ahmedbodi** [comment]
tx messaging

**Comment by crackfoo** [comment]
I tried with it enabled and disabled.

**Comment by ahmedbodi** [comment]
hm, then its not coded right i imagine.

**Comment by ahmedbodi** [comment]
that was the only change i made to get it working with py-strat

**Comment by djspacedevil** [comment]
Hy,

can anybody explain what they are doing?

is that mean python-stratum? or what?

i become the same error with DEM Coin.

10:13:08: *** REJECTED :( eMark block 1377550 1 txs

**Comment by djspacedevil** [comment]
@ahmedbodi  can you please explain. ;)
