### ISSUE TITLE
php5 modules and nginx configuration

### ISSUE THREAD

**Issue by ExEric3** [tpruvot/yiimp#132]
Can I get some example nginx.conf, default sites config example? Also which php5 modules are required?

I did fresh installation yiimp, imported mysql configured serverconfig.php but if i reload main site its empty. In debug.log is all fine without errors. Thanks.

**Comment by tpruvot** [comment]
`       root /var/web;
        access_log  /var/log/yiimp/access.log;
        error_log  /var/log/yiimp/error.log;

        index index.php index.html index.htm;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_intercept_errors on;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_pass   php-fpm;
        }

        location / {
                try_files $uri @rewrite;
        }

        location @rewrite {
                rewrite ^/(.*)$ /index.php?r=$1;
        }
`
