### ISSUE TITLE
Total paid/earned value keeps decreasing.

### ISSUE THREAD

**Issue by MRGiacalone** [tpruvot/yiimp#134]
I noticed that the total paid value from mining (DCR) keeps decreasing overtime when I stop mining. Is this how it is supposed to work?

I thought that the Total Paid Value would let me know how much I have mined to my wallet since I started mining.

**Comment by tpruvot** [comment]
on which site ? on yiimp.ccminer.org earnings are generally definitive (no trading)

**Comment by MRGiacalone** [comment]
Correct it is on http://yiimp.ccminer.org/.

Just to clarify, it is not that I have received less then what I am supposed to receive. I know (from the amount paid to the address) that I have mined a total of ~24 DCR to my wallet since I began to mine. The issue however, is that the value shown as "paid" is far below, and has even decreased when I stop mining for extended periods of time (usually  a few days)
![image](https://user-images.githubusercontent.com/7512698/27544041-f166308a-5a59-11e7-8c72-8b2e9fb5f662.png)

Was that more clear?
I can even give you the address and show you the list of deposits received from mining (privately)

**Comment by tpruvot** [comment]
hmm, the history is kept for months... when did you start ?

**Comment by MRGiacalone** [comment]
I started in February 2017, not that far back.

**Comment by tpruvot** [comment]
indeed, i just checked the tables, and its purged after 2 months... didnt remember that

**Comment by MRGiacalone** [comment]
That was a fast resolution, cheers!
