### ISSUE TITLE
API: 403 - Forbidden

### ISSUE THREAD

**Issue by Xitro01** [tpruvot/yiimp#137]
Hello there. The API of the yiimp ccminer pool is giving a 403 - Forbidden error. Could you fix this?

**Comment by tpruvot** [comment]
It was limited on purpose, There was 3x more activity this week end, and some millions of call per addresses (each 20 seconds) which slow down a lot my server and its efficiency. I need to contact the dev of the tool which do that.

**Comment by Xitro01** [comment]
I retrieve the wallet API once every 10 minutes (tops), I have a cache file and only when I launch my script it will retrieve the info and will first check if the cache is older than 10 minutes or not. Can you add my IP to the whitelist? Or maybe you can block IP's that do more than x connections per minute?

**Comment by tpruvot** [comment]
im working on that... but there is so much queries and different ips that its hard to count them without server load :p

**Comment by Xitro01** [comment]
It is not unusual to block IPs for 5-10 minutes that do alot of requests per minute. Hopefully you can come up with a solution asap! Good luck

**Comment by Xitro01** [comment]
It is not unusual to block IPs for 5-10 minutes that do alot of requests per minute. Hopefully you can come up with a solution asap! Good luck
