### ISSUE TITLE
Unstable hashrate x17 & xvg

### ISSUE THREAD

**Issue by bbekkie** [tpruvot/yiimp#140]
Hello, 

Im located in the Netherlands and am using 2x 1080ti's. The miner im using is alexis cc 1.0. My hashrate notified on the pool ranges from 18 mh to 65 mh. On the ccminer i always see 40,8 mh calculated. What am i doing wrong and what could i possibly do different to make it more stable (the submitted shares). 

My used bat file is as follows:

ccminer -a x17 -i 20 -o stratum+tcp://yiimp.ccminer.org:3737 -u 
pause

**Comment by bbekkie** [comment]
Thanks alot for reading and let me know if you know what i am doing wrong. 

Kind regards, 
Bbekkie

**Comment by bbekkie** [comment]
@tpruvot the problem is that the pool is paying shares based ln the hashrate at that momenr so if the blocks are found at 18 mh dip (while cc miner shows 40,3) i get paid for that while it is possible that i am mining 99% of the time for 40 mh.

**Comment by tpruvot** [comment]
no... doesnt work like that, and stop doing code issue for that
