### ISSUE TITLE
Problem when the web get difficulty Coin.

### ISSUE THREAD

**Issue by DevBiiTz** [tpruvot/yiimp#144]
I added to [HONEY Coin](https://bitcointalk.org/index.php?topic=1823432.0) but i have this problem and i config all daemond and wallet.

_This is a problem with difficulty set:_
![e3653753f00277ceb7912d9ec0be2657](https://user-images.githubusercontent.com/30190276/28602978-91c4db2a-71c1-11e7-8c93-78b404a34d6d.png)

_Problem in Stratum console:_
![86e942bfa83df15284ba1de8c4f5d5fb](https://user-images.githubusercontent.com/30190276/28603016-ccf68f9a-71c1-11e7-8c2e-69d3bbb03795.png)

**Why i have this problem?**

**Possible solutions i think:**

- Need Api to get this.
- Blockexplorer?

**Thank all for help me.** _Sorry my ignorance_.

**Comment by Ondalf** [comment]
Does your coind honey.conf rpcallowip allow you to access from your server to your wallet? That clearly says, ERROR_HTTP_UNAUTHORIZED. Fix your connection from yiimp to wallet. Set correct host address and correct user/pw combination for RPC. Honey works just fine. RPC API is POS. Not POW.
