### ISSUE TITLE
Yiimp. SIGT (Signatum Coin). Block decode failed.

### ISSUE THREAD

**Issue by DeckerSU** [tpruvot/yiimp#149]
Small question about SIGT (Signatum Coin) setup. I'm running a pool and miners was found a block, but it was rejected by signatum. Here is the log:

	18:01:45: SIGT 33751 - diff 28498.734348562 job 371 to 19/19/19 clients, hash 1280.810/2074595.458 in 0.2 ms
	18:01:50: ERROR: rpc_do_call: 127.0.0.1:33334 500
	18:01:50: ERROR Signatum Block decode failed
	18:01:50: *** REJECTED :( Signatum block 33751 59 txs
	18:01:50: submit x.x.x.x (uid 11) 881, 02000000, 598dd4e9, f076783e, 46388.000/1.000
	

	
Plz, help if can, what's the problem? May be in **[x] Txmessage** checkbox in coin setup. It was checked at log's moment. Now i'm turned it off. 

Anyone here have SIGT (Signatum Coin) succefully runned with Yiimp? May be i forget some specific coin settings in admin settings? Thx in advance.

**Comment by DeckerSU** [comment]
Seems i know there is the problem ... stratum create block_hex in client_submit.cpp different ways in POW and POS coins variant. My mistake was in wrong coin type in coin config, i set it to POW instead of POS. According that fact block_hex string before rpc_call submitblock was incorrect. But question is still open, if somebody have SIGT working on Yiimp - can you show here Coin Properties from admin panel, to be sure that i setup it correctly?

p.s. And another question - is any online tool or some python script to decode submitblock's block_hex param?

**Comment by idanfei** [comment]
Can you share the config that you did you find that works ?
