### ISSUE TITLE
PHP not compatible >5.3

### ISSUE THREAD

**Issue by djspacedevil** [tpruvot/yiimp#156]
Non-static method ExplorerController::createUrl() should not be called statically, assuming $this from incompatible context

File db_coinsModel.php

Line 116 $url = ExplorerController::createUrl('/explorer', $urlParams);

i change it but i think the script runs not correct so

**Comment by djspacedevil** [comment]
$ExplorerController = new ExplorerController($this->id);
$url = $ExplorerController->createUrl('/explorer', $urlParams);

**Comment by tpruvot** [comment]
please try :

Yii::app()->createUrl('/explorer', $urlParams);

in which context did you get this error ?

2017-08-17 19:53 GMT+02:00 djspacedevil <notifications@github.com>:

**Comment by djspacedevil** [comment]
Thats helps. 

I get the error in backend on the coinpage 
eg /site/coin/id/1786

**Comment by djspacedevil** [comment]
When you commit it, the problem is fixed with that

**Comment by tpruvot** [comment]
fyi, i dont use PHP <= 5.3, only 5.6.x and more recent

**Comment by djspacedevil** [comment]
i run this on php 5.6.31

**Comment by tpruvot** [comment]
; error_reporting
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

**Comment by djspacedevil** [comment]
PHP Parse error:  syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /var/www/vhosts/***.de/httpdocs/yaamp/core/backend/markets.php on line 256

if is wrong.  `if(!empty(EXCH_BLEUTRADE_KEY))`

must be `if(EXCH_BLEUTRADE_KEY != "")` 

Same on line 403, 489, 574, 559, 657, 835, 919, 1001, 1153 and and

**Comment by djspacedevil** [comment]
file yaamp/core/backend/system 

Line 6 in function BackendDoBackup()

root to  backup dir ?
Why not use __DIR__/../backup or else?
And .htaccess with deny from all
