### ISSUE TITLE
Sunday payout timing

### ISSUE THREAD

**Issue by hashrefinery** [tpruvot/yiimp#162]
The code assumes the Sunday evening payout will occur after 6pm without considering the payout frequency:

https://github.com/tpruvot/yiimp/blob/8c49ab8090223142d71ffd41fde4711a4c7b4ea8/web/yaamp/core/backend/payment.php#L49

If the frequency is longer than 6 hours the lower threshold payout may be skipped.  Also if the frequency is less than 6 hours it may occur twice.

**Comment by hashrefinery** [comment]
If it helps, I think this would fix it:

`if ((strtotime('Sunday 23:59') - time()) < YAAMP_PAYMENTS_FREQ) { // sunday evening, minimum reduced `

**Comment by tpruvot** [comment]
customise it, if you want... its not a big problem to send twice lower amounts
