### ISSUE TITLE
[PATCH] Allow isAdminIP to check DNS names (for using with DynDNS,  NoIP and other DDNS services)

### ISSUE THREAD

**Issue by DeckerSU** [tpruvot/yiimp#166]
Example (in serverconfig.php):

define('YAAMP_ADMIN_IP', '80.236.118.26,90.234.221.11,myhost.dyndns.org'); // samples: "80.236.118.26,90.234.221.11" or "10.0.0.1/8" or myhost.dyndns.org

In this case if user connected from myhost.dyndns.org it resolves to ip in
isAdminIP and also checked.

In yiimp/web/yaamp/core/functions/admin.php change isAdminIP to this:

```
function isAdminIP($ip)
	{
		foreach(explode(',', YAAMP_ADMIN_IP) as $range)
		{
			if (strpos($range, '/')) {
				if(ipCIDRCheck($ip, $range) === true) return true;
			} else if ($range === $ip) {
				return true;
			} else if (checkdnsrr($range, "A")) {
				$dnsrange = gethostbynamel($range);
				if (is_array($dnsrange)) {
					foreach($dnsrange as $resolved) {
						if ($resolved === $ip) return true;
					}
				}
			}
		}
		return false;
	}
```
**p.s.** Higly recommended to check it before use on live systems, but may be somebody needs this.

**Comment by tpruvot** [comment]
You are free to do that on your side, this thing is sensible
