### ISSUE TITLE
instructins

### ISSUE THREAD

**Issue by mintminty59** [tpruvot/yiimp#168]
I would love to use this, are there more detailed instructions I could read thanks

**Comment by crombiecrunch** [comment]
install script https://github.com/crombiecrunch/yiimp

**Comment by mintminty59** [comment]
Thank u a lot !!!!! where are coin demons and wallets stored

**Comment by crombiecrunch** [comment]
this has no coin demons or wallets. It looks like the SQL dump contains some data not related to new installs. 

I am working on updating the script to correct this and a few other not documented anywhere requirements :)

**Comment by mintminty59** [comment]
So it is submitting shares to wallets hosted externally somewhere? Is it worth using your script then importing the SQL dumps from trup github? I would just like to understand how this works and how safe the found blocks are. Many thanks for your responces!

**Comment by mintminty59** [comment]
i could not get it to work.

ubuntu@ubuntu:~$ curl -Lo install.sh https://raw.githubusercontent.com/crombiecrunch/yiimp/master/install.sh bash install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21246  100 21246    0     0  22487      0 --:--:-- --:--:-- --:--:-- 22482
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://advancedsearch2.virginmedia.com/main?ParticipantID=jqlc435patgs4w79dx7g33u8otdryt35&FailedURI=http%3A%2F%2Fbash%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=uk"/><script type="text/javascript">url="http://advancedsearch2.virginmedia.com/main?ParticipantID=jqlc435patgs4w79dx7g33u8otdryt35&FailedURI=http%3A%2F%2Fbash%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=uk";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>curl: (6) Could not resolve host: install.sh

**Comment by mintminty59** [comment]
I tried running script but says I need root, and it says on your instructions not to install as root

**Comment by mintminty59** [comment]
I posted on your github under issues
