### ISSUE TITLE
TCP Password in .config files

### ISSUE THREAD

**Issue by crombiecrunch** [tpruvot/yiimp#170]
Where the heck do i either generate this password or find it? I saw in one of your closed issues you stated
"TCP password should match blocknotify binary one.."

Ive been searching high and low but for the life of me can not solve it.

**Comment by ExEric3** [comment]
Here:

https://github.com/tpruvot/yiimp/blob/next/blocknotify/blocknotify.cpp#L74

And blocknotify.sh as example
