### ISSUE TITLE
unknown method mining.multi_version

### ISSUE THREAD

**Issue by granatgas** [tpruvot/yiimp#175]
hi, what it is?
when some miner connect showing this error
2017-08-30 13:52:31 [91.113.79.202] 1Hx4hVgr1aZfgoyimaaobHyDaz7JRmM6PM, scrypt, bad submits
2017-08-30 13:52:31 [91.113.79.204] unknown method mining.multi_version
and then showing this
./run.sh: line 11: 15251 Segmentation fault      (core dumped) ./stratum config/$1
this is happen on scrypt stratum

**Comment by Ondalf** [comment]
Someone pointed new S9 miner to your pool, while stratum doesn't understand the undocumented function. It all boils to asicboost technology.

**Comment by granatgas** [comment]
i see, so yiimp not supported to handle s9 miner? ok thank you for the answer :D
