### ISSUE TITLE
REJECTED BLOCKS

### ISSUE THREAD

**Issue by mintminty59** [tpruvot/yiimp#177]
21:13:53: *** REJECTED :( Boat block 371331 1 txs
2017-09-01 21:13:53: REJECTED boat block 371331
21:13:53: submit 192.168.0.2 (uid 1) 69, 00000000, 59a9cd8e, 4002d400, 1680490.000/13824.000

**Comment by mintminty59** [comment]
19:38:32: boat 371215 - diff 17.268739154 job 29 to 1/1/1 clients, hash 35.972/1236.144 in 0.2 ms
19:46:05: ERROR: rpc_do_call: 127.0.0.1:14260 500
19:46:05: ERROR Boat Invalid mode
19:46:05: *** REJECTED :frowning: Boat block 371219 2 txs
2017-09-01 19:46:05: REJECTED boat block 371219

**Comment by tpruvot** [comment]
check "has submitblock"
