### ISSUE TITLE
How to setup that the database automatic update with coind  information

### ISSUE THREAD

**Issue by Merratzz** [tpruvot/yiimp#42]
Blocks found and mined and update to database no problem, Blockexplorer ,, all this work. 

But the Coinclientd information about actual diff and actual block number does not update and also the amount of connected nodes.

**Comment by tpruvot** [comment]
could you stop opening new issues please...

**Comment by Merratzz** [comment]
Ou ok sorry for that there was a other open issue? But i work now about 3 Days on this code to get running. Please can you help me?
