### ISSUE TITLE
Profit Switching & Auto Exchange not working

### ISSUE THREAD

**Issue by njbrown09** [tpruvot/yiimp#49]
I have autoexchange enabled (Im mining scrypt) When i use my BTC address, the pool just rejects me.

**Comment by LoRdMiCk** [comment]
same here.. the stratum say " unable to find the wallet for coinid 6..." and "bad mining address"
but if I set bitcoin wallet to "Auto Ready" it work.. but Sha miners (with btc address as user) start mining BTC... and then if I uncheck the "Auto Ready" they stop mining btc and work as it should.. exect for new miner trying to start mining with BTC address they still get reject for "bad mining address"

**Comment by LoRdMiCk** [comment]
I found this in stratum Makefile
 `+# Comment this line to disable address check on login,
 +# if you use the auto exchange feature...
 +CFLAGS += -DNO_EXCHANGE`

I commented this line and remake the stratum and it work fine now! :)
