### ISSUE TITLE
max_ttf - max difficulty ?

### ISSUE THREAD

**Issue by banjochose** [tpruvot/yiimp#52]
Hi wanted to know what "max_ttf" in algo config means ? Firstly I thought it's a max difficulty but while mining it seems to go above the number set in config.

Therefore I am having a question what above feature does ? And if it isn't max difficulty will donate $50 for it to be added.

**Comment by tpruvot** [comment]
max_ttf means max time to find, but... im unsure its really used (was here since beginning)

**Comment by savanahmclaughlinzaz** [comment]
Ok,thanks for clearing it out,also not sure what  "mBTC Coefs per algo (default is 1.0) - serverconfig $configAlgoNormCoef"  does ?

**Comment by tpruvot** [comment]
For your max diff "hack" feature, see web/yaamp/core/backend/coins.php in the backend, you can easily toggle auto_ready on conditions.. 

configAlgoNormCoef are disabled on yiimp, because hackish adjustments are not per algo but per coin.. imo
