### ISSUE TITLE
about compile.

### ISSUE THREAD

**Issue by napoleon2121** [tpruvot/yiimp#57]
hi guys. i am trying to setup this pool (just for the knolege of it.) 
I spend some hours trying to figure this out. 

attempt to open //usr/local/lib/x86_64-linux-gnu/libcudart.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libcudart.a failed
attempt to open //lib/x86_64-linux-gnu/libcudart.so failed
attempt to open //lib/x86_64-linux-gnu/libcudart.a failed
attempt to open //usr/lib/x86_64-linux-gnu/libcudart.so failed
attempt to open //usr/lib/x86_64-linux-gnu/libcudart.a failed
attempt to open //usr/local/lib64/libcudart.so failed
attempt to open //usr/local/lib64/libcudart.a failed
attempt to open //lib64/libcudart.so failed
attempt to open //lib64/libcudart.a failed
attempt to open //usr/lib64/libcudart.so failed
attempt to open //usr/lib64/libcudart.a failed
attempt to open //usr/local/lib/libcudart.so failed
attempt to open //usr/local/lib/libcudart.a failed
attempt to open //lib/libcudart.so failed
attempt to open //lib/libcudart.a failed
attempt to open //usr/lib/libcudart.so failed
attempt to open //usr/lib/libcudart.a failed
attempt to open //usr/x86_64-linux-gnu/lib64/libcudart.so failed
attempt to open //usr/x86_64-linux-gnu/lib64/libcudart.a failed
attempt to open //usr/x86_64-linux-gnu/lib/libcudart.so failed
attempt to open //usr/x86_64-linux-gnu/lib/libcudart.a failed
ld: cannot find -lcudart

what is this. i spend all day to find it out but nothing.

**Comment by napoleon2121** [comment]
make[1]: Leaving directory '/home/napoleon/yiimp/stratum/sha3'
gcc stratum.o db.o coind.o coind_aux.o coind_template.o coind_submit.o util.o list.o rpc.o job.o job_send.o job_core.o merkle.o share.o socket.o coinbase.o client.o client_submit.o client_core.o client_difficulty.o remote.o remote_template.o user.o object.o json.o base58.o rpc_curl.o iniparser/libiniparser.a algos/libalgos.a sha3/libhash.a -lpthread -lgmp -lm -lstdc++ -lmysqlclient -O2 `mysql_config --libs` -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lcurl -lidn -lrtmp -lssl -lcrypto -lssl -lcrypto -Wl,-Bsymbolic-functions -Wl,-z,relro -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -lldap -lz -o stratum
/usr/bin/ld: cannot find -lidn
/usr/bin/ld: cannot find -lrtmp
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lgssapi_krb5
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lk5crypto
/usr/bin/ld: cannot find -lcom_err
/usr/bin/ld: cannot find -llber
/usr/bin/ld: cannot find -lldap
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'stratum' failed
make: *** [stratum] Error 1

also this is the main error

**Comment by auswonk** [comment]
Looks like your system is missing a bunch of libraries needed to compile the stratum binary.

There is not a lot of documentation for this project so you'll need to work through the errors one at a time and keep installing libraries until all the dependencies are resolved.

**Comment by tpruvot** [comment]
you need libcurl4-openssl-dev

for cuda lib, ive no idea how you can have that, your system seems messed up ;)

**Comment by crackfoo** [comment]
Take a minute and search for those missing libraries and install them on
the system. This is not a yiimp issue.

They are dependencies, fullfill them or move along.

**Comment by napoleon2121** [comment]
i installed libcurl4 i installed cuda... i get the same error :P. i am on local vm machine. i can't find the dipentencies .. . i think i will stop my training 📦
