### ISSUE TITLE
How to use the Digibyte multialgos function

### ISSUE THREAD

**Issue by Merratzz** [tpruvot/yiimp#58]
Dear Sir

I need help with the Digibyte. I can use it an found already some Blocks but i have set the algo now only for this Coin to sha256.  The multialgos is enable when i show the Coin in DB.  What i have to file in in ALGOS Typ  =  ? 

How to enable the multialgos so that the coin also in the other stratum run (scrypt,qubit etc.?

**Comment by banjochose** [comment]
You need to add into your conf file 
algo=sha256d #For sha
algo=scrypt #For scrypt
algo=qubit $ For qubit 

and so on,also if you want to run each algo simultaneously you need run each algo in it's own folder with it's own port.

**Comment by Merratzz** [comment]
Ok thanks but for me not clear how to setup in the wallet overwiev page and what to file in in the field Algo. I have the Digibyte Coin once at my overwiepage (Admin Wallet Page ) correct??? Or should i work with the symbols field and official symbol field and then have the same Coin many times for each algo ??  Should there stay unknow algo? or i give only sha or i give all the algos in the field for Digibyte at once setting or at many settings???.  But in background when i start the /stratum/sh run.sh qubit.conf and the scrypt and the sha stratum running as well.  and the multialgo function is crossed in the Database. Its a very nice beautifully software ;-)

**Comment by banjochose** [comment]
it has nothing to do with yaamp, you need to add commands above to cd ~/.digibyte/digibyte.conf
also you can only one at time unless run in multiple folders "one algo per config file"

**Comment by ahmedbodi** [comment]
what your trying to do cant be possible
you have to have 1 coin daemon per algo for the coin
then you make more than 1 digibyte in db with different algo for each

**Comment by Merratzz** [comment]
@ banjochose  ok i add this to my digibyte.conf  

****Blown out***
rpcthreads=8
maxconnections=34
blocknotify=/path/path/path/path/.digibyte/./blocknotify mastermining.net:3434 406 %s  (only SHA Port)? 
algo=sha256d 
algo=scrypt 
algo=qubit 



But what i do set in the blocknotify  --> Port number i can give only one port (and not for each ALGO ) ?

@ahmedbodi  
Ok i have it so,  i have 4 times the digibyte in my DB  with 4 different ID  and Symbol DGB_scyrpt, DGB_sha  DGB_Skein and DGB_qubit. 

The Coin Name and the official symbol name i have set to the same (DGB).  
So i think i was on the right way?
But now the problem is that the stratum only in SHA (becomes the signal from the blocknotify (because set only one port ) correct?

**Comment by tpruvot** [comment]
you need different wallets, their algo cant be changed on the fly

2016-12-29 9:51 GMT+01:00 Merratzz <notifications@github.com>:

**Comment by Merratzz** [comment]
ok really ??? So i have to setup the dameon digibyted  ,   4 times on 4 different servers, i have not 4 different servers?  So and think is so easy to setup..... How to run 4 Wallets on the same server without 4 VM`s?

**Comment by tpruvot** [comment]
with different ports.

**Comment by Merratzz** [comment]
Ok i can change the digibyte source and change the incoming port and Daemon Names and .digibyte path  to other and then compile 3 times to have 3 running daemon. I will try it so....thanks a lot for your support ;-)
