### ISSUE TITLE
Enhancement: Add Livecoin trading functions (0.1 BTC Bounty)

### ISSUE THREAD

**Issue by crackfoo** [tpruvot/yiimp#68]
Hi, 

Is it possible to add Liveocoin deposit/trading/withdraw functions?

Will pay BTC 0.1

Thanks

**Comment by crackfoo** [comment]
:)

**Comment by tpruvot** [comment]
yea, im on it :p

2017-03-10 20:41 GMT+01:00 crackfoo <notifications@github.com>:

**Comment by Tristian** [comment]
How "on it" are you? I did most of the work before I noticed your response.

**Comment by tpruvot** [comment]
oh well in fact got other things to do ;) so please share

**Comment by crackfoo** [comment]
@Tristian push it up and I'll send you the bounty.

**Comment by Tristian** [comment]
@crackfoo Just doing some testing. I'll push something later today.

**Comment by crackfoo** [comment]
Thanks. I'll merge this next week and test. I just left for Vegas so won't be able to pull for now.

**Comment by Tristian** [comment]
@crackfoo For when you approve.
12Nam4bHL6hmce3QYfFH1EnBZWXFqqDo6N

**Comment by tpruvot** [comment]
yea, don't worry, he will send it..

**Comment by crackfoo** [comment]
@Tristian I just merged this now and will watch it for the next 24h or so. 

Thanks!

**Comment by crackfoo** [comment]
so, it has been updating prices, but seems nothing is being sent to the exchange and also the deposit addresses aren't being updated. I even went in to the site and generated them all as I'm not sure the api has a generate option or if just the call to get deposit will get the address if doen't exisit.

Also notice in the coin admin page, even when live coin has the best price, it's at the bottom of the list....

**Comment by crackfoo** [comment]
@Tristian ^^^

**Comment by Tristian** [comment]
Sorry. I'm looking in to it.

**Comment by Tristian** [comment]
The LiveCoin API seems to be pretty unstable. Right now I can make unauthenticated requests, but anything user specific (e.g. deposit addresses) takes a long time to respond. Then gives a 400 with a body containing `SYSTEM_ERROR`.

**Comment by Tristian** [comment]
@crackfoo I haven't been able to replicate any or your problems. It pulls deposit addresses fine. There's not need to have them generated on LiveCoin first.
The coin admin page (http://yiimp/site/coin?id=xxx ?) should be unrelated to any of the code I've  committed. As for nothing being sent to the exchange, I have nothing to test that with at the moment.
It almost sounds like your secret key isn't set or is wrong.
Can you run `yiimp/bin/yiimp exchange apitest` just to be sure ?

**Comment by crackfoo** [comment]
yeah I ran apitest, seemed fine.

livecoin btc: [{"type":"total","currency":"BTC","value":0},{"type":"available","currency":"BTC","value":0},{"type":"trade","currency":"BTC","value":0},{"type":"available_withdrawal","currency":"BTC","value":0}]

**Comment by Tristian** [comment]
Okay, I'll keep looking.

**Comment by crackfoo** [comment]
yeah, it all looks ok. I'll test manually sending coins to the exchange and see if at least that part works to try an narrow down whats not working.

**Comment by crackfoo** [comment]
Caught an exception, guess I didn't quite send enough to meet min trade, but it made the trading crash

Internal Server Error

Undefined variable: min_btc_trade

An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you.

**Comment by crackfoo** [comment]
submitted a PR for it, 

https://github.com/tpruvot/yiimp/pull/98

**Comment by crackfoo** [comment]
With the exchange option to Sell on bid enabled, livecoin is putting the orders in the ASK market and not selling into the BID orders...

**Comment by Tristian** [comment]
I don't know how I missed that...

**Comment by crackfoo** [comment]
So this is what I see int he coin page.. this example is from ARC:

![image](https://cloud.githubusercontent.com/assets/6303714/24357906/a2b5a806-12d5-11e7-8eeb-bac979fa17d3.png)

**Comment by crackfoo** [comment]
And what I see on the site/emptymarkets page:

![image](https://cloud.githubusercontent.com/assets/6303714/24358023/13c82e9c-12d6-11e7-8c90-a223ca908986.png)

**Comment by Tristian** [comment]
@crackfoo Take a look at #99. It should fix a few things, including Livecoin not moving to the top of the list.

I don't know why you have so many empty markets there though. I haven't been able to get a single coin to show up there. And it's strange that you have the same coins multiple times. It's possible that they all have duplicates that _do_ have deposit addresses.

**Comment by crackfoo** [comment]
ok so looks like the market order is now fixed. livecoin prices show in the proper spot.

The empty exchange/deposit address still seems to not work. I restarted memcache but haven't seen them get updated. In my screen you see many since those are multi-algo coins, so they're setup on each of the algos. It should just populate with the same address though like they do on the other exchanges...

**Comment by crackfoo** [comment]
@Tristian my stupidity. I had disabled each livecoin market a long time ago before you added trading cause I could use it and failed to re-enable them. I did and voila, all the addresses got populated. duuuh.

**Comment by crackfoo** [comment]
Thanks

https://blockchain.info/tx/4b8c94af37c10c331e369b7435bcf41e65612aaba5f7e76bf7eddc852d274c14

**Comment by Tristian** [comment]
Aha, I was so confused! Nuked my addresses and re-pulled everything over
and over.

**Comment by crackfoo** [comment]
@Tristian Looks it it's not quite 100% yet...  I don't see it auto trading... I did find that the case is not correct for the do function in the cron jobs:

https://github.com/tpruvot/yiimp/blob/next/web/yaamp/modules/thread/CronjobController.php#L138

while in the exchange/trade you have:

https://github.com/tpruvot/yiimp/blob/next/web/yaamp/core/trading/livecoin_trading.php#L28

But I changed it in the CronjobController to match but I still don't see it trading. Don't see any errors either...

Sending to exchange is working so it's part way there....

**Comment by crackfoo** [comment]
@Tristian automatic withdraw also didn't seem to kick off...

**Comment by Tristian** [comment]
I set up a wallet and stratum yesterday. Trying to mine some coin to test
from start to finish.

**Comment by crackfoo** [comment]
@Tristian Ok I see why BTC withdraw fails... you missed defining the variable:

$btcaddr = YAAMP_BTCADDRESS;

**Comment by Tristian** [comment]
I seem to have missed a lot of things. My apologies

**Comment by Tristian** [comment]
It's too bad most site don't offer a testing API.

On Mar 29, 2017 9:42 AM, wrote:

I seem to have missed a lot of things. My apologies

On Mar 29, 2017 9:41 AM, "crackfoo" <notifications@github.com> wrote:

@Tristian <https://github.com/Tristian> Ok I see why BTC withdraw fails...
you missed defining the variable:

$btcaddr = YAAMP_BTCADDRESS;

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tpruvot/yiimp/issues/68#issuecomment-290093151>, or mute
the thread

**Comment by crackfoo** [comment]
I don't mind pounding out the testing. It'll make it easier for you the next time I look for another exchange ;) ;)

so a lead maybe about the trading issues... while the BTC balance is being updated, the coin balances are not. It's sent some GB to the exchange automatically, and has been confirmed for a while now, but it's not showing the balance when I look at GB coin admin page.... So the trading may think there's nothing to trade since there's not balance showing yet....

**Comment by crackfoo** [comment]
Also, the WD fee was wrong. it should be 0.0005 .  :)

$withdraw_fee = exchange_get($exchange, 'withdraw_fee_btc', 0.0005);
Otherwise, after added the $btcaddr it works it just got the error about insifficent funds since it didn't account for enough fee.

**Comment by crackfoo** [comment]
and maybe now, getting further into some errors. I see now:


2017/03/29 10:09:15 [error] [php] Undefined property: stdClass::$id (/home/zpool/next/web/yaamp/core/trading/livecoin_trading.php:265)
Stack trace:
#0 /home/zpool/next/web/framework-1.1.17/web/CController.php(308): CInlineAction->runWithParams()
#1 /home/zpool/next/web/framework-1.1.17/web/CController.php(286): CronjobController->runAction()
#2 /home/zpool/next/web/framework-1.1.17/web/CController.php(265): CronjobController->runActionWithFilters()
#3 /home/zpool/next/web/framework-1.1.17/web/CWebApplication.php(304): CronjobController->run()
#4 /home/zpool/next/web/run.php(15): CWebApplication->runController()

**Comment by Tristian** [comment]
I think they have access to the fees in the API, so that could be made
dynamic. I doubt they change theirs fees often however.

**Comment by Tristian** [comment]
Needs error checking. It probably sent back an error, so there was no id to
process.

**Comment by crackfoo** [comment]
dynamic?? 

https://github.com/tpruvot/yiimp/blob/next/web/yaamp/core/trading/livecoin_trading.php#L251

**Comment by crackfoo** [comment]
yes, maybe the error was due to the WD actually failing, so no ID to record?

**Comment by crackfoo** [comment]
ok thanks, will look for your changes

**Comment by Tristian** [comment]
@crackfoo #100

**Comment by crackfoo** [comment]
thanks @Tristian  looks like tpruvot suggests one change...

**Comment by crackfoo** [comment]
@Tristian , I've merged the lastest changes and will watch and let you know if it starts trading.

**Comment by crackfoo** [comment]
Still not seeing updated coin balances or trading....

**Comment by Tristian** [comment]
This might help over here Tristian/yiimp@db60f35.

**Comment by crackfoo** [comment]
Ok, that change gets my balances updated as expected... but trading seems not to be kicking in just yet... despite it saying traded 1m ago... the balance still remain on the exchange

![image](https://cloud.githubusercontent.com/assets/6303714/24530814/d56a0532-158a-11e7-9a15-b1a7cef5e8d7.png)

**Comment by Tristian** [comment]
And this? Tristian/yiimp@d373e434
It looks like I had yet another typo in a variable name, so it was failing because it thought it wasn't getting the data it needed.

**Comment by crackfoo** [comment]
heeeeyyy... look what I see now...

[2017-03-31 10:15:17] LiveCoin: Selling market ADZ/BTC, 0.00001551, 0.00001551
[2017-03-31 10:15:21] LiveCoin: Selling market GB/BTC, 0.00001100, 0.00001100
[2017-03-31 10:15:24] runexchange done (livecoin) 49.311 sec

👍

**Comment by Tristian** [comment]
Well that's definitely an improvement.

**Comment by Tristian** [comment]
@crackfoo Tristian/yiimp@51a7923
This really could have gone a lot better...

**Comment by crackfoo** [comment]
haha :)

Looks like a winner now:

[2017-03-31 13:52:46] LiveCoin: Deleting order GoldBlocks 359.9991
[2017-03-31 13:52:46] LiveCoin: Deleting order GoldBlocks 44.9998
[2017-03-31 13:52:46] LiveCoin: Deleting order GoldBlocks 19.9998
[2017-03-31 13:52:46] LiveCoin: Deleting order GoldBlocks 29.9999
[2017-03-31 13:52:46] LiveCoin: Deleting order GoldBlocks 34.9999
[2017-03-31 13:53:05] LiveCoin: Deleting order Adz 160
[2017-03-31 13:53:05] LiveCoin: Deleting order Adz 200
[2017-03-31 13:53:05] LiveCoin: Deleting order Adz 240
[2017-03-31 13:53:05] LiveCoin: Deleting order Adz 400.00001
[2017-03-31 13:53:15] LiveCoin: Selling market ADZ/BTC, 0.00001635, 0.00001635
[2017-03-31 13:53:19] LiveCoin: Selling market GB/BTC, 0.00001091, 0.00001091
[2017-03-31 13:53:28] runexchange done (livecoin) 52.779 sec

**Comment by Tristian** [comment]
For now... :)

**Comment by crackfoo** [comment]
@Tristian you up for another bounty? Want to complete the nova exchange trading? :)

**Comment by Tristian** [comment]
@crackfoo I'm in :)

**Comment by crackfoo** [comment]
Ok, I opened a new issue for it @Tristian #103
