### ISSUE TITLE
Auto enable and disable coins

### ISSUE THREAD

**Issue by LoRdMiCk** [tpruvot/yiimp#76]
Could be nice to add something to auto on and off  mining on some selected coins.. like when pool reach xx h/s enable x coin... or when pool reach xx h/s enable coins with higher then x diff...  thats not a issue but I don't know where to post that..

**Comment by tpruvot** [comment]
I don't really see the point to enable a new coin if the pool has enough speed... but the triggers could be enhanced later to allow things like that

**Comment by LoRdMiCk** [comment]
Cuz some time theres a coin that have a "TTF" of lets say 30min.. and stratum send like half of the pool's hash to that coin  so ttf become 60minutes.. and then some time not able to find any block.. then its like 50% pool hash losted.. that could been used elsewhere..
