### ISSUE TITLE
Stratum Clarification Needed

### ISSUE THREAD

**Issue by abualsaudm** [tpruvot/yiimp#79]
What does it mean when the stratum is outputting the following "not reporting"? Everything seems to be working fine but I don't understand whether this an error or what !!
10:49:35: SwingCoin 462863 not reporting
10:49:56: SwingCoin 462864 not reporting
10:49:57: TIT 1155584 - diff 588698.989413866 job bb to 2/2/2 clients, hash 9421810.236/4040.640 in 0.1 ms
10:50:17: TitCoin 1155584 not reporting
10:50:17: ZayedCoin 149146 not reporting
10:50:18: TIT 1155585 - diff 579048.434144584 job bf to 2/2/2 clients, hash 7537448.189/4040.640 in 0.0 ms
10:50:45: *** ACCEPTED TitCoin 1155585 (diff 2.10813e+06) by 192.168.0.107 (id: 81)
10:50:45: submit 192.168.0.107 (uid 81) 191, ffe30000, 58abf138, 6bc95c97, 2108126.000/16384.000
10:50:59: TitCoin 1155585 not reporting
10:51:00: ZayedCoin 149147 not reporting
10:51:01: TIT 1155586 - diff 599015.882608681 job c3 to 2/2/2 clients, hash 6805775.481/4040.640 in 0.0 ms
10:51:21: Californium 454190 not reporting
10:51:21: ZayedCoin 149148 not reporting

**Comment by LoRdMiCk** [comment]
For me it was blocknotify was not working..

**Comment by LoRdMiCk** [comment]
You need blocknotify bin to the right place and a line like this in every wallet config file.. blocknotify=blocknotify yaamp.com:port coinid %s

**Comment by abualsaudm** [comment]
thank you .. please confirm that the port needs to be the stratum's port ?

**Comment by LoRdMiCk** [comment]
Yes n dont forget to change "coinid" to the right one..

**Comment by abualsaudm** [comment]
I just don't seem to be able to the coined right .. I tried different combination and still cannot get it right

**Comment by tpruvot** [comment]
yep, and the .conf stratum TCP password should match blocknotify binary one..
