### ISSUE TITLE
Stratum Setting Overflow 

### ISSUE THREAD

**Issue by abualsaudm** [tpruvot/yiimp#81]
I keep getting "setting overflow" message on the stratum and "client with no job". How do I get around this? It seems that I am not benefiting from all the hash power in my pool. Please help 

20:20:49: setting overflow
20:20:50: clients with no job
20:20:50: TIT 1156066 - diff 317122.061432845 job 1cb to 5/5/5 clients, hash 22347990.454/22700481.378 in 0.1 ms
20:20:52: clients with no job

**Comment by tpruvot** [comment]
im not an online free support service and github is not a forum

answer: read the code
