### ISSUE TITLE
Add JSON methods

### ISSUE THREAD

**Issue by priestc** [tpruvot/yiimp#84]
As far as I can tell, there is no JSON API abilities for this block explorer. It would be nice to be able to do three things through a JSON API:

1. Get transaction history for address, including transactions that the address sent and received
2. Information for single TX given an TXID. The software already shows this information when you click on a block (see attachment)
3. Push TX. The user sends a raw hex encoded tx, and the block explorer software sends it through the network.

![screen shot 2017-02-25 at 3 55 19 pm](https://cloud.githubusercontent.com/assets/132586/23335870/0e07da5e-fb73-11e6-88fd-1f4fb9e1c02f.png)

Unfortunately the data in the screenshow appears to be embedded into the page in such a way that makes it hard to scrape. A JSON API will make this data usable by other applications.

**Comment by tpruvot** [comment]
no way

**Comment by priestc** [comment]
There is a demand for "db providers" for obscure altcoins. If you make the data available via JSON, more services and wallets can be built on top of that, hence raising the usefulness and value of those coins.
