### ISSUE TITLE
Peercoin crashes yiimp explorer

### ISSUE THREAD

**Issue by crackfoo** [tpruvot/yiimp#9]
Hi, 

When ppcoin is loaded. An attempt to browse the chain with the explorer produces this error:

    2016/01/04 13:29:58 [error] [php] A non well formed numeric value encountered     (/home/crackers/zpool/web/yaamp/core/common/utilConversion.php:147)
    Stack trace:
    #0 /home/pool/web/framework-1.0.8/web/CBaseController.php(119): require()
    #1 /home/pool/web/framework-1.0.8/web/CBaseController.php(88): ExplorerController->renderInternal()
    #2 /home/pool/web/framework-1.0.8/web/CController.php(711): ExplorerController->renderFile()
    #3 /home/pool/web/framework-1.0.8/web/CController.php(649): ExplorerController->renderPartial()
    #4 /home/pool/web/yaamp/modules/explorer/ExplorerController.php(42): ExplorerController->render()
    #5 /home/pool/web/framework-1.0.8/web/actions/CInlineAction.php(32): ExplorerController->actionIndex()
    #6 /home/pool/web/framework-1.0.8/web/CController.php(300): CInlineAction->run()
    #7 /home/pool/web/framework-1.0.8/web/CController.php(278): ExplorerController->runAction()
    #8 /home/pool/web/framework-1.0.8/web/CController.php(257): ExplorerController->runActionWithFilters()
    #9 /home/pool/web/framework-1.0.8/web/CWebApplication.php(335): ExplorerController->run()
    #10 /home/pool/web/framework-1.0.8/web/CWebApplication.php(123): CWebApplication->runController()
    #11 /home/pool/web/framework-1.0.8/base/CApplication.php(134): CWebApplication->processRequest()
    #12 /home/pool/web/index.php(20): CWebApplication->run()
    REQUEST_URI=/explorer?id=1390

**Comment by tpruvot** [comment]
Could try a "return $d;" in the function to get/report me the value ?

2016-01-04 19:36 GMT+01:00 crackfoo <notifications@github.com>:

**Comment by crackfoo** [comment]
I added  $d to the existing return line... and well.. the error went away... though explorer does not show any tx's, but now when I view peercoin, the coin details are blank and I see this error now:

    2016/01/05 07:26:08 [error] [php] reset() expects parameter 1 to be array, boolean given (/home/pool/web/yaamp/modules/site/coin_results.php:194)
    Stack trace:
    #0 /home/pool/web/framework-1.0.8/web/CBaseController.php(88): SiteController->renderInternal()
    #1 /home/pool/web/framework-1.0.8/web/CController.php(711): SiteController->renderFile()
    #2 /home/pool/web/yaamp/modules/site/SiteController.php(382): SiteController->renderPartial()
    #3 /home/pool/web/framework-1.0.8/web/actions/CInlineAction.php(32): SiteController->actionCoin_results()
    #4 /home/pool/web/framework-1.0.8/web/CController.php(300): CInlineAction->run()
    #5 /home/pool/web/framework-1.0.8/web/CController.php(278): SiteController->runAction()
    #6 /home/pool/web/framework-1.0.8/web/CController.php(257): SiteController->runActionWithFilters()
    #7 /home/pool/web/framework-1.0.8/web/CWebApplication.php(335): SiteController->run()
    #8 /home/pool/web/framework-1.0.8/web/CWebApplication.php(123): CWebApplication->runController()
    #9 /home/pool/web/framework-1.0.8/base/CApplication.php(134): CWebApplication->processRequest()
    #10 /home/pool/web/index.php(20): CWebApplication->run()
    REQUEST_URI=/site/coin_results?id=1390

**Comment by crackfoo** [comment]
Also I see now in the "message" column of the coin list "invalid mode" for Peercoin...

**Comment by tpruvot** [comment]
But, not sure about the "invalid mode" wallet error

**Comment by banjochose** [comment]
Yep peercoin give a "invalide mode" message and isn't working well in yaamp.

Bellow reference to the solved issue in different pool
https://github.com/bonesoul/CoiniumServ/issues/442
