### ISSUE TITLE
php7

### ISSUE THREAD

**Issue by wiico** [tpruvot/yiimp#93]
Hi team

Thank's a lot for this work !

Is it possible to look about this log in main.sh :

system:ubuntu 16.04/php7

_<body>
<h1>Internal Server Error</h1>
<h2>curl_setopt(): Disabling safe uploads is no longer supported</h2>
<p>
An internal error occurred while the Web server was processing your request.
Please contact the webmaster to report this problem.
</p>
<p>
Thank you.
</p>
<div class="version">
2017-03-16 21:37:05 </div>
</body>
</html>curl_setopt_

I'm not developper but sysadmin , probably php7   <h2>curl_setopt(): Disabling safe uploads is no longer supported</h2> ?

Best regard.

Np

**Comment by tpruvot** [comment]
yep, i just pushed a commit, for livecoin another commit is in progress..

**Comment by wiico** [comment]
thanks
