### ISSUE TITLE
Deposit addresses never update

### ISSUE THREAD

**Issue by Tristian** [tpruvot/yiimp#97]
As far as I can tell, the expiry for `$exchange.'-deposit_address-check-'.$coin->symbol` is constantly updated to 24 hours from now. So deposit addresses are only updated if it has been at least 24h since the last run of `BackendPricesUpdate()`.
Should `cache()->set...` be within the `if` clause?
[https://github.com/tpruvot/yiimp/blob/b8d68928279f0b5f66a39fc207a03df1bb6d428a/web/yaamp/core/backend/markets.php#L508-L527](url)
#68

**Comment by tpruvot** [comment]
you can also restart the memcache service to test it

**Comment by crackfoo** [comment]
All my livecoin markets (site/emptymarkets) still show empty addresses except the one I manually edited and added the address.

**Comment by Tristian** [comment]
@tpruvot So, the intent is to have the address only update if it hasn't been run for more than 24hrs? And Not just update every 24hrs?
The only way to pull a new address then, is to restart memcached? If that's the case, you can close this.
